name: zalando-spilo-custom

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'https://github.com/zalando/spilo'
          ref: 2.1-p4

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: postgres-appliance
          push: true
          tags: ktsstudio/zalando-spilo-custom:latest
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"