name: zalando-spilo-custom

on:
  push:
    branches:
      - 'main'

env:
  TAG: 2.1-p4

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'zalando/spilo'
          ref: ${{ env.TAG }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: postgres-appliance
          build-args: |
            ADDITIONAL_LOCALES=ru_RU
          push: true
          tags: ghcr.io/ktsstudio/zalando-spilo-custom:${{ env.TAG }}